In [1]:
import numpy as np
a=np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [3]:
a.dtype


dtype('int64')

In [4]:
a.size

4

In [5]:
np.zeros(0,1)

TypeError: Cannot interpret '1' as a data type

In [6]:
a=np.array([1,2,3,4,5,6,7])
a[1:5]

array([2, 3, 4, 5])

In [7]:
a[:4]

array([1, 2, 3, 4])

In [8]:
a[4:]

array([5, 6, 7])

In [9]:
a[: :1]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
a[::2]

array([1, 3, 5, 7])

In [11]:
a=np.array([[1,2,3,4],[4,5,6,7]])
a[0:3,2]

array([3, 6])

In [12]:
a[0:3,1:3]

array([[2, 3],
       [5, 6]])

In [18]:
b=np.array([1,2,3,4],dtype='i4')
print(b)

[1 2 3 4]


In [23]:
arr=np.array([1.1,-2.1,3.1])
new=arr.astype(bool)
print(new)

[ True  True  True]


In [26]:
arr=np.array([1,2,3,4])
x=arr.view()
x[0]=10
print(arr)
print(x)

[10  2  3  4]
[10  2  3  4]


In [27]:
arr=np.array([10,20,30,40],ndmin=5)
print(arr)
print(arr.shape)

[[[[[10 20 30 40]]]]]
(1, 1, 1, 1, 4)


In [28]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.zeros([1,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.full((2,3),18)

array([[18, 18, 18],
       [18, 18, 18]])

In [34]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.full((4,3),18)

array([[18, 18, 18],
       [18, 18, 18],
       [18, 18, 18],
       [18, 18, 18]])

np.random.randint(4,5)

In [38]:
np.random.rand(4,5)

array([[0.85852978, 0.9325755 , 0.2379664 , 0.04999201, 0.29923903],
       [0.92127959, 0.30940121, 0.66855822, 0.8735275 , 0.94509164],
       [0.96142896, 0.35009217, 0.21956454, 0.95870872, 0.04898016],
       [0.50133409, 0.44186953, 0.35107159, 0.05880624, 0.11843137]])

In [40]:
np.random.randint(4,size=(3,3))

array([[1, 1, 3],
       [0, 0, 1],
       [3, 1, 3]])

In [47]:
a=np.array([1,2,3,4])
b=np.array([5,1,4,2])
a+b
a-b
a*b


array([ 5,  2, 12,  8])

In [50]:
a=np.array([[1,2,3,4],[5,4,2,1]])
np.sum(a,axis=0)

array([6, 6, 5, 5])

In [ ]:
print("Hello World")